/**
 * Precompute an index of all structures that have each tag for every namespace
 * This solves a thorny dependency problem
 * The index is generated by /utils/tagIndexGenerator.js
 */


// namespace → tag → id[]
const _index = {};

export function generateTagIndex(namespace, dataset) {
  const ns = (_index[namespace] = {});
  for (const [id, def] of Object.entries(dataset)) {
    for (const tag of def.tags ?? []) {
      (ns[tag] ??= []).push(id);
    }
  }
}

// Return all Ids in namespace that have tag
export function byTag(namespace, tag) {
  return _index[namespace]?.[tag] ?? [];
}

// Returns every tag for given Id in namespace
export function tagsOf(namespace, id, dataset) {
  return dataset[id]?.tags ?? [];
}