/**
 * Precompute an index of all structures that have each tag for every namespace
 * This solves a thorny dependency problem
 * The index is generated by /utils/tagIndexGenerator.js
 */

// namespace → tag → id[]
const _index = {};

// namespace → id[]  (every id registered for that namespace, tagged or not)
const _allIds = {};

export function generateTagIndex(namespace, dataset) {
  const ns = (_index[namespace] = {});
  _allIds[namespace] = Object.keys(dataset);

  for (const [id, def] of Object.entries(dataset)) {
    for (const tag of def.tags ?? []) {
      (ns[tag] ??= []).push(id);
    }
  }
}

// Return all Ids in namespace that have tag
export function byTag(namespace, tag) {
  return _index[namespace]?.[tag] ?? [];
}

// Return every id registered for a namespace (SKILLS, CONDITIONS, LOCATIONS, ...)
export function allIds(namespace) {
  return _allIds[namespace] ?? [];
}

// Returns every tag for given Id in namespace
export function tagsOf(namespace, id, dataset) {
  return dataset[id]?.tags ?? [];
}