/**
 * Precompute an index of all structures that have each tag for every namespace
 * This solves a thorny dependency problem
 * The index is generated by /utils/tagIndexGenerator.js
 */

// namespace → tag → id[]
const _index = {};
// namespace → id[]  (every id registered for that namespace, tagged or not)
const _allIds = {};
// id → tag[] (namespace-agnostic. EntityRegistry already requires uniwue id's)
const _tagsById = {};

export function generateTagIndex(namespace, dataset) {
  const ns = (_index[namespace] = {});
  _allIds[namespace] = Object.keys(dataset);
 
  for (const [id, def] of Object.entries(dataset)) {
    const tags = def.tags ?? [];
    _tagsById[id] = tags;
 
    for (const tag of tags) {
      (ns[tag] ??= []).push(id);
    }
  }
}
 

// Return all Ids in namespace that have tag
export function byTag(namespace, tag) {
  return _index[namespace]?.[tag] ?? [];
}

// Return every id registered for a namespace
export function allIds(namespace) {
  return _allIds[namespace] ?? [];
}

// Return every tag on a given id, namespace-agnostic
export function tagsOf(id) {
  return _tagsById[id] ?? [];
}
 

export function matchesTagQuery(query, tags = []) {
  if (!query || query.length === 0) return true;
  return query.every((clause) =>
    Array.isArray(clause)
      ? clause.some((tag) => tags.includes(tag))
      : tags.includes(clause)
  );
}
